# See ./b for running instructions
version: "3.8"

services:
  # Proxy server
  proxy-server:
    image: $ORG/block-engine-proxy-server:$TAG
    container_name: proxy_server
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy_server
    environment:
      - RUST_BACKTRACE=1
      - PROXY_JSON_RPC_PORT=$PROXY_JSON_RPC_PORT
      - JSON_RPC_URL=$JSON_RPC_URL
      - KEY_PAIR_PATH=/etc/$KEY_PAIR_PATH
    expose:
      - "$PROXY_JSON_RPC_PORT"
    ports:
      - "$PROXY_JSON_RPC_PORT:$PROXY_JSON_RPC_PORT"
    restart: on-failure
    volumes:
      - "$KEY_PAIR_PATH:/etc/$KEY_PAIR_PATH"

#     # If you want to attach to an external network, uncomment the below code
#     # Set the DOCKER_NETWORK environment variable with the name of the external network
#     networks:
#       proxy_server_network: {}

# networks:
#   proxy_server_network:
#     external: true
#     name: $DOCKER_NETWORK
