name: release

on:
  push:
    branches:
      - master

jobs:
  release_proxy_server:
    runs-on: ubuntu-20.04-16c-64g
    defaults:
      run:
        working-directory: ./proxy_server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Sanity Check
        run: |
          cat /proc/cpuinfo

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: test

      - name: Clippy check
        run: cargo clippy --all-features --all-targets --tests -- -D warnings

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./proxy_server
          push: true
          tags: jitolabs/block-engine-proxy-server:${{ github.sha }}, jitolabs/block-engine-proxy-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64,linux/x86_64
